### ISSUE TITLE
IDomainUnitOfWork - not for consumers

### ISSUE THREAD

**Issue by charlessolar** [charlessolar/Aggregates.NET#29]
Currently domain units of work are created even when solely handling events.  This is kind of unexpected because it allows event consumers to load entities from the domain.

Might also be a good idea to re-look into the dual unit of work implementations and attempt to merge them into one.

**Comment by volak** [comment]
Thinking about this one -
Might be time to separate UOWExecutor behavior into 2 pieces.  One to create the domain unit of work if the endpoint handles commands, one to make application unit of work if user defines one.

Would also be nice to add an extension to wireup container for ApplicationUnitOfWork as it can be confusing

**Comment by charlessolar** [comment]
Fixed in v0.17
