### ISSUE TITLE
Any plan to write a comprehensive documentation

### ISSUE THREAD

**Issue by AbdoDabbas** [charlessolar/Aggregates.NET#39]
I'm new to this NServiceBus and EventStore, and this library looks great but the documentation is very poor.
How to know what each extension method means and how to use it?

**Comment by charlessolar** [comment]
@AbdoDabbas  Thanks for checking it out! Sorry I am late to see these github's notification system is pretty bad

The best place to learn how to use this library is via the samples https://github.com/volak/Aggregates.NET/tree/master/samples

and the example apps

- https://github.com/charlessolar/TodoMVC-DDD-CQRS-EventSourcing
- https://github.com/charlessolar/eShopOnContainersDDD

Unfortunately if you are new to NServiceBus and EventStore you will have a learning curve with those libraries first.  This library mainly builds on top of those two and gives you the DDD toolset and design.

I would get started by standing up the todo app and just playing with the messaging. Adding commands, implementing reactions to commands (events) etc.

Feel free to reach out if you have any difficulties!  This library is not 1.0 yet so my focus hasn't been on documentation or a fixed API but there is a roadmap to get there eventually!
