### ISSUE TITLE
Adding EventStore to my endpoint fails

### ISSUE THREAD

**Issue by AbdoDabbas** [charlessolar/Aggregates.NET#40]
Hi,  
I'm trying to add EventStore to my endpoint but it's failing with this exception:
```
2020-08-02 14:08:42.505 ERROR Moving message '54a9f936-25fa-4eb0-afc6-ac0b00b7a829' to the error queue 'error' because processing failed due to an exception:
System.Collections.Generic.KeyNotFoundException: No item found in behavior context with key: Aggregates.UnitOfWork.IDomain
   at NServiceBus.Extensibility.ContextBag.Get[T](String key)
   at NServiceBus.Extensibility.ContextBag.Get[T]()
........
```

In the handler endpoint, I copied the code from the ToDo example (from the Domain\Endpoin.cs) to initialize the endpoint.
In the sender endpoint I modified the `CommandToDomain` method (copied it from Infrastructure\Extensions\BusExtensions.cs) to be like this:
```
public static async Task CommandToDomain<T>(this IMessageSession bus, T message, bool timeout = true) where T: MyBaseCommand
{
	try
	{
		var options = new SendOptions();
		options.SetDestination("DomainDestName");

		Task task = bus.Send(message, options);

		await Task
			.WhenAny(Task.Delay(TimeoutSeconds), task)
			.ConfigureAwait(false);

		if (task.IsFaulted && task.Exception != null)
			throw task.Exception.InnerException;

		if (!task.IsCompleted)
			throw new CommandTimeoutException("Command timed out");
	}
	catch (Exception ex)
	{
		// TODO: Logger
		throw;
	}
}
```
P.S:
I don't know if this is related but I even added the same `Mutator` used in the ToDo sample but request is not reaching `MutateIncoming` method at all.

I don't know what's missing or what should I specify in other files (as I said I copied the Endpoint.cs file to my project)

**Comment by AbdoDabbas** [comment]
I suspected there's a backward compatibility issue between version `0.15.35` (which sample TODO is using) and the latest version `0.15.62` .. which I was trying to use, something is missing, I upgraded all the Aggregates.NET NuGet packages in the TODO example (except for the `EventStore.Client` I kept it on v5.0.9), and run the app .. I go the same error again.
So, I think the registration of the `IDomain` interface to use the concrete class of the EventStore is not happening, or something like that.

Can you please advise on this.

**Comment by AbdoDabbas** [comment]
In the TODO sample (after upgrading NServiceBus to 7.3.0) I figured out that it's throwing the following exception:
```
System.Exception: 'Could not enumerate all types for 'Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

It looks like you may be missing binding redirects in the config file for the following assemblies:
Aggregates.NET, Version=0.15.1.0, Culture=neutral, PublicKeyToken=null
For more information see http://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.100).aspx'

**Stack Trace:**
   at NServiceBus.Hosting.Helpers.AssemblyScanner.AddTypesToResult(Assembly assembly, AssemblyScannerResults results)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies()
   at NServiceBus.EndpointCreator.Scan(AssemblyScanner assemblyScanner, SettingsHolder settings)
   at NServiceBus.EndpointCreator.GetAllowedTypes(String path, SettingsHolder settings)
   at NServiceBus.EndpointCreator.PerformAssemblyScanning(EndpointConfiguration endpointConfiguration)
   at NServiceBus.EndpointCreator.FinalizeConfiguration(EndpointConfiguration endpointConfiguration)
   at NServiceBus.EndpointCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IConfigureComponents configureComponents)
   at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IConfigureComponents configureComponents)
   at Aggregates.NSBConfigure.<>c__DisplayClass0_0.<NServiceBus>b__0(Configure c) in C:\Projects\temp\Aggregates.NET\src\Aggregates.NET.NServiceBus\NSBConfigure.cs:line 83
```

**Comment by charlessolar** [comment]
@AbdoDabbas Thanks for the report and email!  I will have to check it out strange that it works in 7.2.4..

I will update the packages on those apps and try it for myself.

**Comment by charlessolar** [comment]
@AbdoDabbas Looking over things my recommendation right now is to stay on version 7.2.4.  7.3 has some breaking changes I have to incorporate into Aggregates.Net itself

Should be pretty easy once I have some time to look at it and setup a test environment

**Comment by AbdoDabbas** [comment]
Thanks a lot, @charlessolar .. what do you think if you can explain the issue and the fix maybe I can do the changes on behalf of you and do a commit (if I could manage to do the changes).

Thanks for your work.

**Comment by charlessolar** [comment]
Ok got it - the NSB folks deprecated a feature component I was using to position registration of my internal stuff. https://github.com/Particular/NServiceBus/pull/5493

I fixed that and a couple other breaking changes from EventStore and its good to go now.

One thing to note though if you are using the TodoMVC sample.  Make sure FakeItEasy remains at version 5.4.0.  Don't update to 6.0.0 or 5.4.1 / 5.5.0.  AutoFixture and FakeItEasy folks are having issues keeping a stable api

**Comment by AbdoDabbas** [comment]
This is really awsome, really appreciate the quick response and fix :) this library is the core of our system.

**Comment by charlessolar** [comment]
Glad you like it feel free to reach out for any other issues or questions!
