### ISSUE TITLE
Writing to EventStore is taking so much time, sometimes it doesn't work, and events don't reach directly to Application endpoint.

### ISSUE THREAD

**Issue by AbdoDabbas** [charlessolar/Aggregates.NET#46]
I'm facing an issue trying to build the Application endpoint that will have handlers and listen to events that's triggered in the Domain endpoint using `Apply` method.  
* When I run both endpoints together:
I was facing an issue that sometimes command reach the domain handler and the method `Apply` but is not saved in the  EventStore (I can't see it in the "Stream Browser" window), then it started working.

* When I run only the Domain endpoint without running the Application endpoint, all works perfectly.

* When I run again the Domain endpoint+Application endpoint the domain works and data saved in ES but event doesn't reach the Application, BUT if I turned off the Application endpoint and run it again, I receive ALL  the events that I Domain triggered from the beginning of the test (all stacked there), even after receiving them, If I re-run the Application endpoint again I receive them again.

The tests all done using the ToDo sample code.

**Comment by charlessolar** [comment]
There's a few things you can check -

* Events are saved when the message processing is ending - you can place a breakpoint on message handling and pause every command to make sure the events are being written

* verify the event projections in the eventstore UI are correct. They are setup automatically but you'll want to see 2 different projections with different sets of events they handle

* after receiving events at the application - verify the persistent subscription shows X events of X processed. Meaning they were all processed and ACKd correctly

**Comment by AbdoDabbas** [comment]
So for point 1:
I think you mean to take a look at the EventStore -> StreamBrowser and make sure the models I triggered in the `Apply` are there, if that's the case, yes I checked and they're there and also I see a stream named after the `application` endpoint and inside it the events I triggered in the domain.

Point2:
I'll check.

Point3:
Sorry but where to check this? when I put break point in the application handler I receive the events (all of them again and again) and I do return without doing any action inside the handler at all, do I need to to any thing to ACK correctly?

**Comment by charlessolar** [comment]
No you dont have to ACK them Agg.Net does that.  You should just verify that under persistent subscriptions in the eventstore UI it shows that you processed all your events correctly.

That would be the only reason why you'd receive the events more than once - if the events were not successfully processed that is

**Comment by charlessolar** [comment]
@AbdoDabbas Figure out the issue?

**Comment by AbdoDabbas** [comment]
No actually, it sometimes show up sometimes go.
I tried cleaning up the EventStore db and logs and even RabbitMQ and didn't
happen, even though before it elwas. On my colleague machine it happened.
I wasn't able to reproduce it to be able to figure out what may cause the
issue.

>

**Comment by AbdoDabbas** [comment]
I left the project for a while and came back to it.
I figured out why sometimes the events don't reach the Application endpoint:
[Connections for Persistent Subscriptions are lost if the console debugged using VisualStudio.](https://github.com/EventStore/EventStore/issues/2854).
This isdue I opened on

**Comment by AbdoDabbas** [comment]
Hi @charlessolar,
Regarding the issue of setting timeout, any advice ?!

**Comment by charlessolar** [comment]
Oh yes I absolutely agree if you are pausing the debugger in an app you'll need to set the timeouts very long.

Agg.net doesn't handle connecting to the event store itself but the logic is simple using the event store api.
You'll also need to set the timeouts on the server settings as well
