### ISSUE TITLE
Taking snapshot to speed reading from EventStore

### ISSUE THREAD

**Issue by AbdoDabbas** [charlessolar/Aggregates.NET#47]
Hi @charlessolar,

I'm facing slowness reading from EventStore after an aggregate root raised many events, reply them looks like takes sometime.

Is there way from the Aggregates.Net to take a snapshot of the events to speed things up?

I tried inside the Entity to call `Snapshot` but didn't get any thing.

**Comment by charlessolar** [comment]
Absolutely! There is a sample here
https://github.com/charlessolar/Aggregates.NET/tree/master/samples/2.%20Snapshots

There's a method to override on state objects to start snapshotting

**Comment by AbdoDabbas** [comment]
I tried this, but I couldn't find the snapshot took by the EventStore in the Stream page.

**Comment by charlessolar** [comment]
Snapshots are stored in a different stream - check `$ce-SNAPSHOT` which is a system category stream which should list all snapshots taken
